   <!--./ NAV BAR END -->
	
    <!--./ HOME SECTION END -->
  
    <!--./ ABOUT SECTION END -->
 
    <!--./ DONARS TESTIMONIALS END --><br/><br/>
    <div id="port-folio" class="pad-top-botm" style="background:#fff" >
        <div class="container">
		<ol class="breadcrumb">
			 <li><a href="index.html">Home</a></li>
			 <li class="active"><a><?php echo $title; ?></a></li>
		 </ol>
            <div class="row text-center ">
              <div class="top-sellers"><br/>
			    				
								
							
								<article class="post post_mod-j clearfix" id="join" style="padding:10%; padding-top:0px">
									
									<h3 class="entry-title ui-title-">TERMS</h3>
											<p style="font-size:16px; text-align:justify; font-family:'Helvetica Neue', Helvetica, Arial, sans-serif "> 
								
<ul style="font-size:16px; text-align:justify; ">

<li>•	If you register for a given amount category, you will be required to bring five people that will register for the same amount category. </li>
<br/>
<li>•	If you bring any person that want to register for a different amount category, the system will automatically register you for that different category and you will get entitlement for both category but since you didn’t register for the second category, your entitlement will be after the sixth person you introduced into the system in that second category. You can run concurrently as many categories as possible in this way.</li>
<br/>
<li>•	After you get your first entitlement, you can still be bringing people into the system and as soon as you get another set of five people in the same category, you will get another entitlement.</li>
<br/>
<li>•	Your entitlement is four-fifth (4/5) the amount generated by the five people you brought into the system and you can use it to buy any desired product or service either from us or from any other preferred choice but the system will make the cash available.</li> 
<br/>
<li>•	You can get a refund and close your account if you are not interested in the system any longer but it will only be with immediate effect when you registered directly with the system otherwise you have to wait for the person that brought you to introduce another person as your replacement, but if you have introduced at least one person into the system, your refund will also be immediate. However, the company does not expect that anyone could want to back out of this kind of system but to maintain openness and our integrity; a refund will be made on request if the above conditions are met. You can sue us if will fail.</li>
<br/>
</ul>

</p>
</article><!-- end post -->
								
            </div>
          
        </div>
    </div>

<br/><br/>